rvm: 2.1

sudo: required

addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

env:
  matrix:
    - PLATFORM='standalone-debian-78'
    - PLATFORM='standalone-debian-82'
    - PLATFORM='standalone-ubuntu-1404'
    - PLATFORM='standalone-centos-67'
    - PLATFORM='standalone-centos-72'
    - PLATFORM='cluster-debian-78'
    - PLATFORM='cluster-debian-82'
    - PLATFORM='cluster-ubuntu-1404'
    - PLATFORM='cluster-centos-67'
    - PLATFORM='cluster-centos-72'

install:
  - sudo apt-get update -yq
  - sudo apt-get install -yq linux-headers-generic virtualbox virtualbox-dkms --fix-missing
  -  sudo dpkg-reconfigure virtualbox-dkms
  - sudo wget -nv https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
  - sudo dpkg -i vagrant_1.8.1_x86_64.deb
  - sudo apt-get install -yf

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - rubocop -v
  - rspec -v
  - foodcritic -V
  - VBoxManage --version
  - /opt/chefdk/embedded/bin/chef gem install chef-sugar

script:
  - rspec
  - rubocop
  - foodcritic .
  - kitchen verify ${PLATFORM}

